### ISSUE TITLE
error when activating app

### ISSUE THREAD

**Issue by michielbdejong** [ChrisHoyer/NextCloud_Timesheet#1] opened 2021-10-12 12:35 UTC
Hi! Great that you're working on this!
I cloned your repo, copied the `timesheet` folder into the `apps/` folder of my nextcloud instance on localhost for testing (t uses SQLite for the database), then tried to activate it but got this error:
![Screenshot 2021-10-12 at 14 32 51](https://user-images.githubusercontent.com/408412/136956892-7789dd9a-b825-401f-b009-7da817467639.png)

Any idea what might be happening? Is it maybe trying twice to initialise the database?

**Comment by ChrisHoyer** [comment] 2021-10-12 13:56
Hi!

Thanks for the reply and feedback. It's nice to hear that others are also interested in this app. So far I have only tested this on my end, so there may still be some bugs. This issue looks like a bug in `lib/Migration/Version000660Date202106050924.php` during the migiration. I will take care of this and fix it as soon as possible.

**Comment by ChrisHoyer** [comment] 2021-10-12 20:47
I just did some googling for this problem as I could not reproduce it on my system. It seems that SQLLite does not allow to use the same index in different tables, while mySQL does. So in short: both tables `timesheet_reports` and `timesheet_records` share the same index `timesheet_user_id_index`. 

I'm on it

**Comment by ChrisHoyer** [comment] 2021-12-21 20:38
Should be fixed in Version 0.6.62

**Closed as completed by ChrisHoyer** 2021-12-21 20:38 UTC
Labels: bug
